// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protocol_1.proto
// Protobuf C++ Version: 5.29.5

#include "protocol_1.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace protocol {

inline constexpr CharacterBase::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : level_{0},
        job_{static_cast< ::protocol::JobType >(0)},
        second_job_{static_cast< ::protocol::SecondJobType >(0)},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR CharacterBase::CharacterBase(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct CharacterBaseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CharacterBaseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CharacterBaseDefaultTypeInternal() {}
  union {
    CharacterBase _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CharacterBaseDefaultTypeInternal _CharacterBase_default_instance_;
}  // namespace protocol
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_protocol_5f1_2eproto[2];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_protocol_5f1_2eproto = nullptr;
const ::uint32_t
    TableStruct_protocol_5f1_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::protocol::CharacterBase, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::protocol::CharacterBase, _impl_.level_),
        PROTOBUF_FIELD_OFFSET(::protocol::CharacterBase, _impl_.job_),
        PROTOBUF_FIELD_OFFSET(::protocol::CharacterBase, _impl_.second_job_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::protocol::CharacterBase)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::protocol::_CharacterBase_default_instance_._instance,
};
const char descriptor_table_protodef_protocol_5f1_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\020protocol_1.proto\022\010protocol\"k\n\rCharacte"
    "rBase\022\r\n\005level\030\001 \001(\005\022\036\n\003job\030\002 \001(\0162\021.prot"
    "ocol.JobType\022+\n\nsecond_job\030\003 \001(\0162\027.proto"
    "col.SecondJobType*F\n\007JobType\022\014\n\010JOB_NONE"
    "\020\000\022\017\n\013JOB_WARRIOR\020\001\022\014\n\010JOB_MAGE\020\002\022\016\n\nJOB"
    "_ARCHER\020\003*`\n\rSecondJobType\022\020\n\014SEC_JOB_NO"
    "NE\020\000\022\023\n\017SEC_JOB_PALADIN\020\001\022\024\n\020SEC_JOB_ARC"
    "HMAGE\020\002\022\022\n\016SEC_JOB_SNIPER\020\003b\006proto3"
};
static ::absl::once_flag descriptor_table_protocol_5f1_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_protocol_5f1_2eproto = {
    false,
    false,
    315,
    descriptor_table_protodef_protocol_5f1_2eproto,
    "protocol_1.proto",
    &descriptor_table_protocol_5f1_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_protocol_5f1_2eproto::offsets,
    file_level_enum_descriptors_protocol_5f1_2eproto,
    file_level_service_descriptors_protocol_5f1_2eproto,
};
namespace protocol {
const ::google::protobuf::EnumDescriptor* JobType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_protocol_5f1_2eproto);
  return file_level_enum_descriptors_protocol_5f1_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t JobType_internal_data_[] = {
    262144u, 0u, };
bool JobType_IsValid(int value) {
  return 0 <= value && value <= 3;
}
const ::google::protobuf::EnumDescriptor* SecondJobType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_protocol_5f1_2eproto);
  return file_level_enum_descriptors_protocol_5f1_2eproto[1];
}
PROTOBUF_CONSTINIT const uint32_t SecondJobType_internal_data_[] = {
    262144u, 0u, };
bool SecondJobType_IsValid(int value) {
  return 0 <= value && value <= 3;
}
// ===================================================================

class CharacterBase::_Internal {
 public:
};

CharacterBase::CharacterBase(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:protocol.CharacterBase)
}
CharacterBase::CharacterBase(
    ::google::protobuf::Arena* arena, const CharacterBase& from)
    : CharacterBase(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE CharacterBase::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void CharacterBase::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, level_),
           0,
           offsetof(Impl_, second_job_) -
               offsetof(Impl_, level_) +
               sizeof(Impl_::second_job_));
}
CharacterBase::~CharacterBase() {
  // @@protoc_insertion_point(destructor:protocol.CharacterBase)
  SharedDtor(*this);
}
inline void CharacterBase::SharedDtor(MessageLite& self) {
  CharacterBase& this_ = static_cast<CharacterBase&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* CharacterBase::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) CharacterBase(arena);
}
constexpr auto CharacterBase::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(CharacterBase),
                                            alignof(CharacterBase));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull CharacterBase::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_CharacterBase_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &CharacterBase::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<CharacterBase>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &CharacterBase::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<CharacterBase>(), &CharacterBase::ByteSizeLong,
            &CharacterBase::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(CharacterBase, _impl_._cached_size_),
        false,
    },
    &CharacterBase::kDescriptorMethods,
    &descriptor_table_protocol_5f1_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* CharacterBase::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 0, 2> CharacterBase::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::protocol::CharacterBase>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int32 level = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(CharacterBase, _impl_.level_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(CharacterBase, _impl_.level_)}},
    // .protocol.JobType job = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(CharacterBase, _impl_.job_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(CharacterBase, _impl_.job_)}},
    // .protocol.SecondJobType second_job = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(CharacterBase, _impl_.second_job_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(CharacterBase, _impl_.second_job_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 level = 1;
    {PROTOBUF_FIELD_OFFSET(CharacterBase, _impl_.level_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // .protocol.JobType job = 2;
    {PROTOBUF_FIELD_OFFSET(CharacterBase, _impl_.job_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // .protocol.SecondJobType second_job = 3;
    {PROTOBUF_FIELD_OFFSET(CharacterBase, _impl_.second_job_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void CharacterBase::Clear() {
// @@protoc_insertion_point(message_clear_start:protocol.CharacterBase)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.level_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.second_job_) -
      reinterpret_cast<char*>(&_impl_.level_)) + sizeof(_impl_.second_job_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* CharacterBase::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const CharacterBase& this_ = static_cast<const CharacterBase&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* CharacterBase::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const CharacterBase& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:protocol.CharacterBase)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 level = 1;
          if (this_._internal_level() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_level(), target);
          }

          // .protocol.JobType job = 2;
          if (this_._internal_job() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteEnumToArray(
                2, this_._internal_job(), target);
          }

          // .protocol.SecondJobType second_job = 3;
          if (this_._internal_second_job() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteEnumToArray(
                3, this_._internal_second_job(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:protocol.CharacterBase)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t CharacterBase::ByteSizeLong(const MessageLite& base) {
          const CharacterBase& this_ = static_cast<const CharacterBase&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t CharacterBase::ByteSizeLong() const {
          const CharacterBase& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:protocol.CharacterBase)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // int32 level = 1;
            if (this_._internal_level() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_level());
            }
            // .protocol.JobType job = 2;
            if (this_._internal_job() != 0) {
              total_size += 1 +
                            ::_pbi::WireFormatLite::EnumSize(this_._internal_job());
            }
            // .protocol.SecondJobType second_job = 3;
            if (this_._internal_second_job() != 0) {
              total_size += 1 +
                            ::_pbi::WireFormatLite::EnumSize(this_._internal_second_job());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void CharacterBase::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<CharacterBase*>(&to_msg);
  auto& from = static_cast<const CharacterBase&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:protocol.CharacterBase)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_level() != 0) {
    _this->_impl_.level_ = from._impl_.level_;
  }
  if (from._internal_job() != 0) {
    _this->_impl_.job_ = from._impl_.job_;
  }
  if (from._internal_second_job() != 0) {
    _this->_impl_.second_job_ = from._impl_.second_job_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void CharacterBase::CopyFrom(const CharacterBase& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protocol.CharacterBase)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CharacterBase::InternalSwap(CharacterBase* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CharacterBase, _impl_.second_job_)
      + sizeof(CharacterBase::_impl_.second_job_)
      - PROTOBUF_FIELD_OFFSET(CharacterBase, _impl_.level_)>(
          reinterpret_cast<char*>(&_impl_.level_),
          reinterpret_cast<char*>(&other->_impl_.level_));
}

::google::protobuf::Metadata CharacterBase::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace protocol
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_protocol_5f1_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
