// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protocol_1.proto
// Protobuf C++ Version: 5.29.5

#ifndef protocol_5f1_2eproto_2epb_2eh
#define protocol_5f1_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029005
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_protocol_5f1_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_protocol_5f1_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_protocol_5f1_2eproto;
namespace protocol {
class CharacterBase;
struct CharacterBaseDefaultTypeInternal;
extern CharacterBaseDefaultTypeInternal _CharacterBase_default_instance_;
}  // namespace protocol
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace protocol {
enum JobType : int {
  JOB_NONE = 0,
  JOB_WARRIOR = 1,
  JOB_MAGE = 2,
  JOB_ARCHER = 3,
  JobType_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  JobType_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool JobType_IsValid(int value);
extern const uint32_t JobType_internal_data_[];
constexpr JobType JobType_MIN = static_cast<JobType>(0);
constexpr JobType JobType_MAX = static_cast<JobType>(3);
constexpr int JobType_ARRAYSIZE = 3 + 1;
const ::google::protobuf::EnumDescriptor*
JobType_descriptor();
template <typename T>
const std::string& JobType_Name(T value) {
  static_assert(std::is_same<T, JobType>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to JobType_Name().");
  return JobType_Name(static_cast<JobType>(value));
}
template <>
inline const std::string& JobType_Name(JobType value) {
  return ::google::protobuf::internal::NameOfDenseEnum<JobType_descriptor,
                                                 0, 3>(
      static_cast<int>(value));
}
inline bool JobType_Parse(absl::string_view name, JobType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<JobType>(
      JobType_descriptor(), name, value);
}
enum SecondJobType : int {
  SEC_JOB_NONE = 0,
  SEC_JOB_PALADIN = 1,
  SEC_JOB_ARCHMAGE = 2,
  SEC_JOB_SNIPER = 3,
  SecondJobType_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  SecondJobType_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool SecondJobType_IsValid(int value);
extern const uint32_t SecondJobType_internal_data_[];
constexpr SecondJobType SecondJobType_MIN = static_cast<SecondJobType>(0);
constexpr SecondJobType SecondJobType_MAX = static_cast<SecondJobType>(3);
constexpr int SecondJobType_ARRAYSIZE = 3 + 1;
const ::google::protobuf::EnumDescriptor*
SecondJobType_descriptor();
template <typename T>
const std::string& SecondJobType_Name(T value) {
  static_assert(std::is_same<T, SecondJobType>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to SecondJobType_Name().");
  return SecondJobType_Name(static_cast<SecondJobType>(value));
}
template <>
inline const std::string& SecondJobType_Name(SecondJobType value) {
  return ::google::protobuf::internal::NameOfDenseEnum<SecondJobType_descriptor,
                                                 0, 3>(
      static_cast<int>(value));
}
inline bool SecondJobType_Parse(absl::string_view name, SecondJobType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<SecondJobType>(
      SecondJobType_descriptor(), name, value);
}

// ===================================================================


// -------------------------------------------------------------------

class CharacterBase final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:protocol.CharacterBase) */ {
 public:
  inline CharacterBase() : CharacterBase(nullptr) {}
  ~CharacterBase() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(CharacterBase* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(CharacterBase));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR CharacterBase(
      ::google::protobuf::internal::ConstantInitialized);

  inline CharacterBase(const CharacterBase& from) : CharacterBase(nullptr, from) {}
  inline CharacterBase(CharacterBase&& from) noexcept
      : CharacterBase(nullptr, std::move(from)) {}
  inline CharacterBase& operator=(const CharacterBase& from) {
    CopyFrom(from);
    return *this;
  }
  inline CharacterBase& operator=(CharacterBase&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CharacterBase& default_instance() {
    return *internal_default_instance();
  }
  static inline const CharacterBase* internal_default_instance() {
    return reinterpret_cast<const CharacterBase*>(
        &_CharacterBase_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(CharacterBase& a, CharacterBase& b) { a.Swap(&b); }
  inline void Swap(CharacterBase* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CharacterBase* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CharacterBase* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<CharacterBase>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const CharacterBase& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const CharacterBase& from) { CharacterBase::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(CharacterBase* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "protocol.CharacterBase"; }

 protected:
  explicit CharacterBase(::google::protobuf::Arena* arena);
  CharacterBase(::google::protobuf::Arena* arena, const CharacterBase& from);
  CharacterBase(::google::protobuf::Arena* arena, CharacterBase&& from) noexcept
      : CharacterBase(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kLevelFieldNumber = 1,
    kJobFieldNumber = 2,
    kSecondJobFieldNumber = 3,
  };
  // int32 level = 1;
  void clear_level() ;
  ::int32_t level() const;
  void set_level(::int32_t value);

  private:
  ::int32_t _internal_level() const;
  void _internal_set_level(::int32_t value);

  public:
  // .protocol.JobType job = 2;
  void clear_job() ;
  ::protocol::JobType job() const;
  void set_job(::protocol::JobType value);

  private:
  ::protocol::JobType _internal_job() const;
  void _internal_set_job(::protocol::JobType value);

  public:
  // .protocol.SecondJobType second_job = 3;
  void clear_second_job() ;
  ::protocol::SecondJobType second_job() const;
  void set_second_job(::protocol::SecondJobType value);

  private:
  ::protocol::SecondJobType _internal_second_job() const;
  void _internal_set_second_job(::protocol::SecondJobType value);

  public:
  // @@protoc_insertion_point(class_scope:protocol.CharacterBase)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const CharacterBase& from_msg);
    ::int32_t level_;
    int job_;
    int second_job_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_protocol_5f1_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// CharacterBase

// int32 level = 1;
inline void CharacterBase::clear_level() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.level_ = 0;
}
inline ::int32_t CharacterBase::level() const {
  // @@protoc_insertion_point(field_get:protocol.CharacterBase.level)
  return _internal_level();
}
inline void CharacterBase::set_level(::int32_t value) {
  _internal_set_level(value);
  // @@protoc_insertion_point(field_set:protocol.CharacterBase.level)
}
inline ::int32_t CharacterBase::_internal_level() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.level_;
}
inline void CharacterBase::_internal_set_level(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.level_ = value;
}

// .protocol.JobType job = 2;
inline void CharacterBase::clear_job() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.job_ = 0;
}
inline ::protocol::JobType CharacterBase::job() const {
  // @@protoc_insertion_point(field_get:protocol.CharacterBase.job)
  return _internal_job();
}
inline void CharacterBase::set_job(::protocol::JobType value) {
  _internal_set_job(value);
  // @@protoc_insertion_point(field_set:protocol.CharacterBase.job)
}
inline ::protocol::JobType CharacterBase::_internal_job() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::protocol::JobType>(_impl_.job_);
}
inline void CharacterBase::_internal_set_job(::protocol::JobType value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.job_ = value;
}

// .protocol.SecondJobType second_job = 3;
inline void CharacterBase::clear_second_job() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.second_job_ = 0;
}
inline ::protocol::SecondJobType CharacterBase::second_job() const {
  // @@protoc_insertion_point(field_get:protocol.CharacterBase.second_job)
  return _internal_second_job();
}
inline void CharacterBase::set_second_job(::protocol::SecondJobType value) {
  _internal_set_second_job(value);
  // @@protoc_insertion_point(field_set:protocol.CharacterBase.second_job)
}
inline ::protocol::SecondJobType CharacterBase::_internal_second_job() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::protocol::SecondJobType>(_impl_.second_job_);
}
inline void CharacterBase::_internal_set_second_job(::protocol::SecondJobType value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.second_job_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace protocol


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::protocol::JobType> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::protocol::JobType>() {
  return ::protocol::JobType_descriptor();
}
template <>
struct is_proto_enum<::protocol::SecondJobType> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::protocol::SecondJobType>() {
  return ::protocol::SecondJobType_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // protocol_5f1_2eproto_2epb_2eh
